export enum ActionTypes {
  INSERT = "INSERT",
  DELETE = "DELETE",
  UPDATE = "UPDATE",
  ARCHIVE = "ARCHIVE",
  RESTORE = "RESTORE",
  SHOW_ACTIVE_NOTES = "SHOW_ACTIVE_NOTES",
  SHOW_ARCHIVED_NOTES = "SHOW_ARCHIVED_NOTES",
  SHOW_NOTE_FORM = "SHOW_NOTE_FORM",
  CLOSE_NOTE_FORM = "CLOSE_NOTE_FORM",
  GET_TASK_TYPES = "GET_TASK_TYPES",
}
